name: CI

# githubフローに従って、mainブランチにpush(かPRが作成)されたときに実行
on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE
  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE

jobs:
  # ビルドジョブ
  build:
    runs-on: ubuntu-latest
    steps:
      # チェックアウト
      - uses: actions/checkout@v2

      # JDKのセットアップ
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      # local.propertiesの設定
      - name: Set up local.properties
        env:
          OWNER_MAIL_ADDRESS: ${{ secrets.OWNER_MAIL_ADDRESS }}
          OWNER_PHONE_NUMBER: ${{ secrets.OWNER_PHONE_NUMBER }}
        run: |
          sed "s|\${OWNER_MAIL_ADDRESS}|$OWNER_MAIL_ADDRESS|g; s|\${OWNER_PHONE_NUMBER}|$OWNER_PHONE_NUMBER|g;" local.default.properties > local.properties

      # Gradleのキャッシュ復元
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 依存関係の出力
      - name: Displays the Android dependencies of the project
        run: ./gradlew androidDependencies

      # コンパイル
      - name: Run Compile
        run: ./gradlew assembleDebug

  # テストジョブ
  test:
    runs-on: ubuntu-latest
    steps:
      # チェックアウト
      - uses: actions/checkout@v2

      # JDKのセットアップ
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      # local.propertiesの設定
      - name: Set up local.properties
        env:
          OWNER_MAIL_ADDRESS: ${{ secrets.OWNER_MAIL_ADDRESS }}
          OWNER_PHONE_NUMBER: ${{ secrets.OWNER_PHONE_NUMBER }}
        run: |
          sed "s|\${OWNER_MAIL_ADDRESS}|$OWNER_MAIL_ADDRESS|g; s|\${OWNER_PHONE_NUMBER}|$OWNER_PHONE_NUMBER|g;" local.default.properties > local.properties


      # Gradleのキャッシュ復元
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # テスト
      - name: Test with Gradle
        run: ./gradlew test --stacktrace

      # テスト結果とコードカバレッジのアップロード
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: results
          path: |
            **/build/reports/tests/**/*
            **/build/reports/test-results/**/*
          if-no-files-found: warn
          retention-days: 14

  lint:
    runs-on: ubuntu-latest
    steps:
      # チェックアウト
      - uses: actions/checkout@v2

      # JDKのセットアップ
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      # local.propertiesの設定
      - name: Set up local.properties
        env:
          OWNER_MAIL_ADDRESS: ${{ secrets.OWNER_MAIL_ADDRESS }}
          OWNER_PHONE_NUMBER: ${{ secrets.OWNER_PHONE_NUMBER }}
        run: |
          sed "s|\${OWNER_MAIL_ADDRESS}|$OWNER_MAIL_ADDRESS|g; s|\${OWNER_PHONE_NUMBER}|$OWNER_PHONE_NUMBER|g;" local.default.properties > local.properties


      # 静的解析
      - name: Run Inspection
        run: ./gradlew lint

      # 結果の表示
      - name: Show results on GitHub
        uses: yutailang0119/action-android-lint@v1
        with:
          xml_path: '**/build/reports/lint-results-*.xml'

      # アーティファクトへアップロード
      - name: Upload results Artifact
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: results
          path: |
            **/build/reports/lint-results-*.html
            **/build/reports/lint-results-*.xml
          if-no-files-found: error
          retention-days: 14

  ktlint:
    runs-on: ubuntu-latest
    steps:
      # チェックアウト
      - uses: actions/checkout@v2

      # インストール
      - name: Install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.42.1/ktlint
          chmod a+x ktlint
          sudo mv ktlint /usr/local/bin/

      # 静的解析
      - name: Lint with ktlint
        run: ktlint --reporter=checkstyle,output=build/ktlint-report.xml
        continue-on-error: true

      # 結果の表示
      - name: Show results on GitHub
        uses: yutailang0119/action-ktlint@v1
        with:
          xml_path: build/ktlint-report.xml

      # アーティファクトへアップロード
      - name: Upload results Artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: results
          path: |
            **/build/ktlint-report.xml
          if-no-files-found: error
          retention-days: 14